/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Virtual Museums of Małopolska (https://sketchfab.com/WirtualneMuzeaMalopolski)
license: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
source: https://sketchfab.com/3d-models/vis-p35p-pistol-babe98e5485241f1971c10544f2ff796
title: Vis P35(p) pistol
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    ['02___Default']: THREE.MeshStandardMaterial
  }
}

export function Pistol(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/pistol/pistol.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, -Math.PI / 2, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials['02___Default']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/pistol/pistol.gltf')
